### ISSUE TITLE
Blue screen problem on 19044

### ISSUE THREAD

**Issue by Me19m4** [SoftSec-KAIST/NTFuzz#3]
Win10 19044 32-bit operating system

Hooker Driver triggers unreadable errors when hooking functions。

I remember fixing this a few months ago, but the code was lost。

It seems to be because ExAllocatPoolWithTag, but I forget the exact fix.

**Comment by jchoi2022** [comment]
Sorry, I forgot to post a reply on this issue.
Thank you for reporting the bug!
I'm currently busy with other tasks, but I will look into the problem when I have some time.
